# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.2
# Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/york/cs/net/xilinx_vivado-2016.2_ise-14.7_x86-64-1/Vivado_HLS/2016.2/../../Vivado/2016.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z010clg400-1 ../xilinx_com_hls_toplevel_1_0.zip
